services:
  app:
    image: guaguaupop:0.0.6
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/guaguaupop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 333333
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: guaguaupop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 333333
    volumes:
        - C:/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432